# Generated by Django 5.0 on 2023-12-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoriy',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='yangilikklar',
            name='category',
        ),
    ]
