# Generated by Django 5.0 on 2023-12-19 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_rename_categoriy_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangilikklar',
            name='category',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='asosiy.category'),
        ),
    ]
