# Generated by Django 5.0 on 2023-12-19 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_yangilikklar_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangilikklar',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.category'),
        ),
    ]
