# Generated by Django 5.0 on 2023-12-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Yangilikklar',
            new_name='Yangiliklar',
        ),
    ]
